### PR TITLE
fix queries and add the ability to do pagination 

### PR DESCRIPTION
**Pull request by RahavLussato**
hi ,
i fixed some issues with the queries but the main feature is that
i exposed watchEvent and unWatchEvent to have the ability,
to call it from component and then play with the queries so i can have pagination.

for example i did on my user lists component that every click on next page will call this.props.firebase.watchEvent, with : 

``` javascript
_getNextData = (event) => {
        event.preventDefault();
        this.props.firebase.watchEvent('value', `xxxxxxx/xxxxxxxx/#orderByChild=full_name&startAt=${_prevLastUser[_pageCounter].val().full_name}=${_prevLastUser[_pageCounter].key()}'&limitToFirst=10`);
    };
```

and every click on prev page button will call : 

``` javascript
_getPrevData = (event) => {
        event.preventDefault();
        var prevPageCounter = _pageCounter;
        _pageCounter = _prevLastUser[_pageCounter-1] ? _pageCounter-1 : _pageCounter;

        if (prevPageCounter != _pageCounter) {
            this.props.firebase.watchEvent('value', `xxxxxxxxx/xxxxxxxxxx/#orderByChild=full_name&endAt=${_prevLastUser[_pageCounter].val().full_name}=${_prevLastUser[_pageCounter].key()}'&limitToLast=10`);
        }
    };
```

and on the render after i calc the table current rows i managed the pages like: 

``` javascript
if (usersSnapshot) {
            if (!_prevLastUser[_pageCounter]) {
                _prevLastUser[_pageCounter] = lastUser;
            } else if (_prevLastUser[_pageCounter].key() != lastUser.key()) {
                _pageCounter += 1;
                _prevLastUser[_pageCounter] = lastUser;
            }
        }
```

be aware that i initilazied two global vars outside the component:

``` javascript
var _pageCounter = 1;
var _prevLastUser = [];
```

all of that now works so i have material ui table that fetch data from firebase with pagination and the data is on redux :)

its not finished yet i need to do more tests to it to check when to unWatch and how the amount of listeners will affect performance and live updates.

### CODE REVIEW

**Comment by RahavLussato** [comment]
@tiberiuc i saw your question, by pagination i mean to fetch the data by chunks, on my case i fetch every time only 10 objects and have next and prev buttons.

**Comment by tiberiuc** [comment]
let me know when you finish with tests and I will merge it

Also can you also write a doc about who that should be used

**Comment by tiberiuc** [comment]
I prefer to not keep build files on git. building the package is done by prepublish script in package.json
 /build folder is ignored for git in .gitignore but is not present in .npmignore that mean whenever a `npm publish` is done it will build the project and then will be published into npmjs so when you are doing `npm install redux-react-firebase` the build folder will come as well and it is not build by users

**Comment by RahavLussato** [comment]
its caused to me some issues when i work on my fork and did npm install it didn't run the prepublish script, i got errors because of that on heroku that build folder is missing also i got errors that heroku didn't recognise babel.
you can see in most repos that dist folder is part of the project like here : https://github.com/tylermcginnis/re-base
i think that its better to have the dist folder instead to build on every npm install.

**Comment by RahavLussato** [comment]
so i ended with my tests its look good :),
when i'll have time i'll write gist about how to do that.

**Comment by tiberiuc** [comment]
perfect, I will merge this PR now and when you have time you can write the docs into a new PR into QUERYING.md

**Pull request merged**
