### PR TITLE
Dynamically calculate paths based on latest `props`

### PR DESCRIPTION
**Pull request by maxkomarychev**
The idea is to use function passed to decorator each time new props arrive to wrapped component.

### CODE REVIEW

**Comment by maxkomarychev** [comment]
@tiberiuc please review.

**Comment by prescottprue** [comment]
+1
@tiberiuc Is there anything missing to accept?

**Comment by prescottprue** [comment]
@maxkomarychev I made [redux-firebasev3](https://github.com/prescottprue/redux-firebasev3) to merge changes into in the meantime, it would be great to see this PR on there. Once @tiberiuc is back around we can combine them.

**Comment by maxkomarychev** [comment]
@prescottprue I believe https://github.com/prescottprue/redux-firebasev3 should be a _fork_ of this repo as this will simplify applying patches back and forth and will look nicer in history later once it merged into mainline as now these are two _different_ repos from Git perspective that don't share common commits, what do you think?

**Comment by prescottprue** [comment]
@maxkomarychev There were a few people including myself that needed a new namespace for npm so that we could install the updated version for other projects. Instead of pointing to a forked repo in my package file, I copied over the repo (including history) into a new repo name.

I can merge changes from it back over to my fork of the library, just haven't had a reason to yet.

Feel free to post an issue on that repo about this if you want since this discussion no longer matches this issue.

**Side Note:** It looks like [re-base](https://www.npmjs.com/package/re-base) now supports v3 of firebase

**Pull request merged**
