### PR TITLE
add queryId and fix unset watchers

### PR DESCRIPTION
**Pull request by RahavLussato**
i fixed some bugs with unset and add also new optional param to path that called "queryId",
with this param you can give ID to your watcher and then if you want to listen only to the last query (when do multiple queries on same page for example on paging), it will check if the id have listener it will do unset to the prev watch and set up a new watch.

### CODE REVIEW

**Comment by RahavLussato** [comment]
@tiberiuc  i see that the branch has conflicts but i can't see them, please notify me if you have trouble with this one.

**Comment by tiberiuc** [comment]
it was a conflict in build/compose.js

**Comment by tiberiuc** [comment]
it was a conflict in build/compose.js

**Comment by tiberiuc** [comment]
please don;t forget to write some docs about queries so other people will know how to use it

**Pull request merged**
