### PR TITLE
fix #63 (doNotParse behavior in source/actions.js)

### LINKED ISSUE #63: doNotParse: Undocumented, often unwanted behavior
For some reason, `equalTo` query arguments sometimes get parsed as integers, even if they are not integers, leading to troublesome side-effects.

I used `orderByChild` in combination with `equalTo` on user ids, sending me on a two-hour bug hunt where the query worked for some users and not work for others; only to find out that for this query combination, [the `equalTo` handler in actions.js](https://github.com/tiberiuc/redux-react-firebase/blob/master/source/actions.js#L148), by default, parses their parameter as integer using `parseInt`, like so:

```js
case 'equalTo':
  let equalToParam = !doNotParse ? parseInt(param[1]) || param[1] : param[1]
```

 This sort of logic has multiple problems:

1. It does not work for strings that begin with integers, such as firebase-generated ids: `parseInt('11asfkvvjjjj--add')` actually returns `11`. That's right, `parseInt` ain't a quitter; if it doesn't work for the whole thing, it settles for any number prefix in the string.
1. It does not work for `0`: `parseInt("0") || "0"` actually returns the string `"0"` instead of number `0`.

I propose a simple fix, borrowed from [this StackOverflow discussion on integer string validation](http://stackoverflow.com/a/32539708/2228771):

```js
function isIntString(val) {
    return val === "" + ~~val;
}
// ...
let equalToParam = (!doNotParse && isIntString(param[1])) ? parseInt(param[1]) : param[1];
```

It's not perfect but certainly a lot better. Maybe just working with numbers in general, rather than int only would be better?

PS: There are a few more questions related to the rationale behind this design decision:

1. You only assume that integers need parsing. What about floats or other sorts of special values that might have accidentally ended up string-encoded?

1. And also: why is `doNotParse` not the default? Shouldn't special parsing behavior that might make your queries not behave the way they would when using vanilla firebase, be opt-in, rather than opt-out?

### PR DESCRIPTION
**Pull request by Domiii**
fix #63

### CODE REVIEW

**Comment by prescottprue** [comment]
@Domiii Had the same issue and handled it in [`react-redux-firebase`](https://github.com/prescottprue/react-redux-firebase). The API is very similar to `redux-react-firebase`, so that may work for you until this is merged.

**Comment by Domiii** [comment]
@prescottprue  What is https://github.com/prescottprue/react-redux-firebase? How do the two relate? Is that your personal fork? Or?

**Comment by prescottprue** [comment]
@Domiii It was originally my fork, but we needed extra functionality (including populate). Since then the two have sort of diverged based on user's needs.

This question is more thoroughly answered [in the FAQ](https://github.com/prescottprue/react-redux-firebase#faq).

**Comment by Domiii** [comment]
Thanks a lot! I'm checking it out right now. After all, your project seems a lot more feature complete and in more active development than this one.

I don't want to badmouth anyone - I'd rather like to think that as engineers, we have to confront reality the way it is! :/

**Comment by prescottprue** [comment]
@Domiii they are all good repos :rofl: 

As the FAQ states, I think they both serve there purposes, and at the end of the day it is all about sharing everything to help everyone as much as possible. I think we can all say we are happy to see issues solved, regardless of how.

**Pull request merged**
