### PR TITLE
add support for firebase query

### PR DESCRIPTION
**Pull request by RahavLussato**
currently only:
- orderByChild
- limitToFirst
- limitToLast

### CODE REVIEW

**Comment by RahavLussato** [comment]
after investigating that i see that orderBy is only guaranteed when using forEach() to go over it (by firebase docs: https://www.firebase.com/docs/web/api/datasnapshot/foreach.html)
so order by will not work with this version only limits

**Comment by RahavLussato** [comment]
i managed to fix orderBy by deliver the snapshot also with the data, i'll upload that tomorrow.

**Comment by RahavLussato** [comment]
so i tested that now and its works :),
to work with that you'll need to : 
1. get the firebase snapshot on connect by snapshotToJS.
2. loop over the snapshot with .forEach and then use .val() to get the ordered value or .key() to get the key

**Comment by tiberiuc** [comment]
I will test it and see how the listeners affect each other, have you tested that. For example have 2 components on the same page one watching for /data and the other watch for /data#orderBy=... both components should work then remove one of them and the remaining one should have the listeners working

**Comment by RahavLussato** [comment]
@tiberiuc i'm trying to implement pagination now, do you have any experience with that stuff ?

**Comment by tiberiuc** [comment]
@RahavLussato what do you mean by pagination ?

**Pull request merged**
